---
deployment:
  tasks:
    - source /home/tvfcoijb/virtualenv/test/3.11/bin/activate && cd /home/tvfcoijb/test && python manage.py collectstatic --noinput
    - touch /home/tvfcoijb/test/passenger_wsgi.py