# Generated by Django 6.0 on 2026-06-23 06:57

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_session_alter_student_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['class_obj', django.db.models.functions.text.Length('roll_number'), 'roll_number'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
