# Generated by Django 6.0 on 2026-06-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth_bs',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
