# Generated by Django 6.0 on 2026-06-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_date_of_birth_bs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
    ]
