# Generated by Django 4.2.16 on 2026-07-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_gender'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('symbol_number', ''), _negated=True), fields=('school', 'symbol_number'), name='unique_school_symbol_number'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('registration_number', ''), _negated=True), fields=('school', 'registration_number'), name='unique_school_registration_number'),
        ),
    ]
