# Generated by Django 4.2.16 on 2026-07-23 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_unique_school_symbol_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_fcm_tokens', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Device Token',
                'verbose_name_plural': 'Student Device Tokens',
            },
        ),
    ]
