# Generated by Django 6.0 on 2026-06-20 09:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_value', models.CharField(blank=True, choices=[('AB', 'Absent'), ('WH', 'Withheld'), ('EX', 'Exempted')], max_length=2, null=True)),
                ('theory_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('internal_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('present_days', models.PositiveIntegerField(blank=True, null=True)),
                ('total_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_marks', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_entries', to='exams.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_entries', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_entries', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_entries', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Mark Entry',
                'verbose_name_plural': 'Mark Entries',
                'ordering': ['student__roll_number', 'subject__order'],
                'unique_together': {('exam', 'student', 'subject')},
            },
        ),
    ]
