# Generated by Django 4.2.16 on 2026-07-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_markentry_session'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='markentry',
            index=models.Index(fields=['school', 'exam', 'student'], name='marks_marke_school__afeed2_idx'),
        ),
    ]
