# Generated by Django 6.0 on 2026-06-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
