# Generated by Django 6.0 on 2026-06-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['numeric_level', 'name', 'section'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='class',
            name='numeric_level',
            field=models.PositiveIntegerField(default=0, help_text='Sort order (e.g., 1 for Nursery, 10 for Class 10)'),
        ),
    ]
