# Generated by Django 6.0 on 2026-06-25 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_options_class_numeric_level'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classteacher',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_roles', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='classteacher',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
