# Generated by Django 4.2.16 on 2026-07-17 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_email'),
        ('classes', '0004_classteacher_teacher_alter_classteacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='classteacher',
            name='class_obj',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_class_teacher', to='classes.class'),
        ),
    ]
