# Generated by Django 4.2.16 on 2026-07-17 05:47

from django.db import migrations


def migrate_class_teachers_forward(apps, schema_editor):
    Class = apps.get_model('classes', 'Class')
    ClassTeacher = apps.get_model('classes', 'ClassTeacher')
    
    for cls in Class.objects.all():
        try:
            # We changed related_name to legacy_class_teacher
            legacy = ClassTeacher.objects.get(class_obj=cls)
            if legacy.teacher:
                cls.class_teacher = legacy.teacher
                cls.save()
        except ClassTeacher.DoesNotExist:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_class_class_teacher_alter_classteacher_class_obj'),
    ]

    operations = [
        migrations.RunPython(migrate_class_teachers_forward, migrations.RunPython.noop),
    ]
