# Generated by Django 4.2.16 on 2026-07-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_migrate_class_teachers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassTeacher',
        ),
    ]
