# Generated by Django 6.0 on 2026-06-20 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('credit_hour', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('subject_type', models.CharField(choices=[('COMPULSORY', 'Compulsory'), ('OPTIONAL', 'Optional'), ('NON_CREDIT', 'Non-Credit')], default='COMPULSORY', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in ledger')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classes.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['order', 'name'],
                'unique_together': {('school', 'class_obj', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SubjectMarkingStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_theory', models.BooleanField(default=True)),
                ('theory_full_marks', models.PositiveIntegerField(default=100)),
                ('theory_pass_marks', models.PositiveIntegerField(default=40)),
                ('has_internal', models.BooleanField(default=False)),
                ('internal_full_marks', models.PositiveIntegerField(blank=True, default=25, null=True)),
                ('internal_pass_marks', models.PositiveIntegerField(blank=True, default=10, null=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marking_structure', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Subject Marking Structure',
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Student Subject Enrollment',
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
