# Generated by Django 6.0 on 2026-06-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='credit_hour',
        ),
        migrations.AddField(
            model_name='subject',
            name='has_practical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='practical_credit_hour',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='theory_credit_hour',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=4),
        ),
    ]
