# Generated by Django 6.0 on 2026-06-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_remove_subject_credit_hour_subject_has_practical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='practical_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
