# Generated by Django 6.0 on 2026-06-21 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_subscription_end_date_and_more'),
        ('subjects', '0003_subject_practical_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.academicsession'),
        ),
    ]
