# Generated by Django 4.2.16 on 2026-07-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_subject_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='practical_credit_hour',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='theory_credit_hour',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=4),
        ),
    ]
