# Generated by Django 4.2.16 on 2026-07-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_alter_subject_practical_credit_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='practical_full_marks',
            field=models.DecimalField(blank=True, decimal_places=2, default=25.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='practical_pass_marks',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='theory_full_marks',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subject',
            name='theory_pass_marks',
            field=models.DecimalField(decimal_places=2, default=35.0, max_digits=5),
        ),
    ]
