# Generated by Django 4.2.16 on 2026-07-17 05:47

from django.db import migrations


def migrate_marks_forward(apps, schema_editor):
    Subject = apps.get_model('subjects', 'Subject')
    SubjectMarkingStructure = apps.get_model('subjects', 'SubjectMarkingStructure')
    
    for subject in Subject.objects.all():
        try:
            sms = SubjectMarkingStructure.objects.get(subject=subject)
            subject.theory_full_marks = sms.theory_full_marks
            subject.theory_pass_marks = sms.theory_pass_marks
            if subject.has_practical:
                subject.practical_full_marks = sms.internal_full_marks
                subject.practical_pass_marks = sms.internal_pass_marks
            else:
                subject.practical_full_marks = 0
                subject.practical_pass_marks = 0
            subject.save()
        except SubjectMarkingStructure.DoesNotExist:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_subject_practical_full_marks_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_marks_forward, migrations.RunPython.noop),
    ]
