# Generated by Django 4.2.16 on 2026-07-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_migrate_marks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectMarkingStructure',
        ),
    ]
