# Generated by Django 4.2.16 on 2026-07-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_remove_school_exam_head_name_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='schools.academicsession'),
        ),
    ]
