# Generated by Django 4.2.16 on 2026-07-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherSubject',
        ),
    ]
