# Generated by Django 6.0 on 2026-06-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examclass',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
