# Generated by Django 4.2.16 on 2026-07-06 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_exam_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examclass',
            options={'ordering': ['class_obj__numeric_level', 'class_obj__name', 'class_obj__section'], 'verbose_name': 'Exam Class'},
        ),
    ]
