# Generated by Django 4.2.16 on 2026-07-11 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_examclass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_aggregate',
            field=models.BooleanField(default=False, help_text="If true, this exam's marks are aggregated from other exams."),
        ),
        migrations.CreateModel(
            name='ExamAggregationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_percentage', models.DecimalField(decimal_places=2, help_text='Weight in percentage, e.g., 20.00 for 20%', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aggregate_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregation_rules', to='exams.exam')),
                ('source_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_aggregations', to='exams.exam')),
            ],
            options={
                'verbose_name': 'Exam Aggregation Rule',
                'ordering': ['source_exam__start_date'],
                'unique_together': {('aggregate_exam', 'source_exam')},
            },
        ),
    ]
