# Generated by Django 4.2.16 on 2026-07-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_exam_is_aggregate_examaggregationrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='end_date',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_date',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
