# Generated by Django 6.0 on 2026-06-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
