# Generated by Django 6.0 on 2026-06-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='grading_system',
            field=models.CharField(choices=[('NEB', 'NEB Grading')], default='NEB', max_length=10),
        ),
    ]
