# Generated by Django 4.2.16 on 2026-07-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_supportticket_ticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_attachments/'),
        ),
    ]
