# Generated by Django 4.2.16 on 2026-07-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_ticketmessage_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='exam_head_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='grading_system',
        ),
    ]
