# Generated by Django 4.2.16 on 2026-07-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_remove_school_exam_head_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects_guide_pdf', models.FileField(blank=True, null=True, upload_to='system_docs/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
