# Generated by Django 4.2.16 on 2026-07-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
