# Generated by Django 4.2.16 on 2026-07-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_school_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='app_logo',
            field=models.ImageField(blank=True, null=True, upload_to='system_branding/'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='app_name',
            field=models.CharField(blank=True, default='E-Natija', max_length=100),
        ),
    ]
