# Generated by Django 4.2.16 on 2026-07-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_systemsetting_app_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='dashboard_background',
            field=models.ImageField(blank=True, null=True, upload_to='school_backgrounds/'),
        ),
        migrations.AddField(
            model_name='school',
            name='dashboard_background_opacity',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Opacity of the background image (0.00 to 1.00)', max_digits=3),
        ),
    ]
