# Generated by Django 4.2.16 on 2026-07-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_school_dashboard_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
